"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

# M1:
# transfer chars to ascii code
# get sum of all chars of s and t, the difference between sums is the extra char
# transfer difference to char
# ord("a") -> 65 chr(65) -> "a" by ASCII
M2:
use xor
"""
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        res = 0
        for i in xrange(len(s)):
            res -= ord(s[i])
        for i in xrange(len(t)):
            res += ord(t[i])
        return chr(res)
